### PR TITLE
Audiostreaming

### PR DESCRIPTION
**Pull request by Trojaner25**
Unity can stream / play wav and ogg on PC. More information here: https://docs.unity3d.com/353/Documentation/Manual/AudioFiles.html
(Sadly no mp3 support)

Requested from RoyIL:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/185

Added SteamCalls (Prefixed with AudioSteamCall_xxxxx, e.g. AudioSteamCall_Play):
```csharp
Play(string url, int playbackId, bool isStream, bool autoPlay)
SetVolume(int playbackId, float volume)
AttachToPlayer(int playbackId, CSteamID target)
AttachToVehicle(int playbackId, uint vehId) 
Deattach(int playbackId)
SetPosition(int playbackId, Vector3 pos) 
SetMaxDistance(int playbackId, float maxDistance) 
SetMinDistance(int playbackId, float minDistance)
Resume(int playbackId)
Pause(int playbackId) 
Destroy(int playbackId)
SetLoop(int playbackId, bool loop)
DestroyAll() 
SetMute(int playbackId, bool mute)
SetSpatialBlend(int playbackId, float blend) 
SetMode(int playbackId, int mode)
SetSpread(int playbackId, float spread) 
SetDopplerLevel(int playbackId, float level) 
SetRollofMode(int playbackId, int mode)
```

Currently max. 5 streams can play at the same time.
When leaving the server, everything audio-related gets disposed and destroyed.

Example usage scenarios:
```
* /radio which streams some radio station
* Adding custom sound to players, vehicles, buildings etc... 
* Vehicles with real radio
* Admins doing random events and playing music
* ???
...
etc
```

Compared to Workshop this is much more flexible (only downloaded on-demand, can be modified / updated easily, easier to setup etc) and allows *streaming* endless audio. Also options like `minDistance`, `maxDistance`, `volume`, `position`, `parent` can be set dynamically.

TODO:
* [x] Check if channels match on server and client (they do, ch# 2)
* [x] Check if streaming works at all
* [x] Cache downloadable sound files (`isStream == false`) instead of streaming them (so it doesn't have to redownload them every time)
* [x] Make demo plugin
* [x] Check if other channels are still working (maybe the new channel messed up player channels?)
* [x] Adjust Interval
* [x] Test all new SteamCalls
* [x] Check what happens when download fails

Bugs:
- Log somestimes get spammed while some audio is streaming:
`Error: Cannot create FMOD::Sound instance for resource  )¦°÷, (Unsupported file or audio format. )`.
Might be Unity related / not fixable
- isStream == true doesn't work

### CODE REVIEW

**Comment by SDGNelson** [comment]
This sounds like a useful feature and I'm sure other plugins would make use of it. You might run in to some issues with syncing the steam channel component's ID (that feature hasn't been touched since mid 2014) but I'm sure we could sort it out.

**Comment by Trojaner25** [comment]
At the moment the channel component ID is always at 2 from my testings

**Comment by SDGNelson** [comment]
Perfect then, that should work fine.

**Comment by Trojaner25** [comment]
Demo plugin:
https://github.com/Trojaner25/AudioStreamPlugin

**Comment by Trojaner25** [comment]
Status update:
All SteamCalls except position related ones work.

For some reason positional audio does not work, so the following SteamCalls wont too:
```
AttachAudioToPlayer(int playbackId, CSteamID target)
AttachAudioToVehicle(int playbackId, uint vehId)
DeattachAudio(int playbackId) 
SetAudioPosition(int playbackId, Vector3 pos) 
SetAudioMaxDistance(int playbackId, float maxDistance)
SetAudioMinDistance(int playbackId, float minDistance)
```

**Comment by Trojaner25** [comment]
https://youtu.be/Y6FXiwfmNOM

**Comment by Trojaner25** [comment]
The branch is ready for merge - however because of some Unity limitations streaming live audio (e.g. radios) doesn't work correctly. So I disabled it for now.
Everything else (e.g. streaming single files, positional audio etc) works.

**Comment by Trojaner25** [comment]
Another PR which was not merged after 16 days

**Comment by SDGNelson** [comment]
Oh! Strange: previous GitHub alerts about this PR were bringing me to:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community-Module/pull/5/files
so I didn't think there were any new comments.

I'll merge and upload this to preview momentarily.

**Comment by SDGNelson** [comment]
I made one change before merging which was to prevent instantiating the abstract module/player component bases. (Unity was complaining about that.) The upload is now in-progress and will be on the Steam preview branch once completed.

**Comment by Trojaner25** [comment]
Thanks 😁

**Pull request merged**
