### PR TITLE
Add Harmony & Restructure Project

### PR DESCRIPTION
**Pull request by Trojaner25**
[Harmony](https://github.com/pardeike/Harmony) is a MIT-licensed library for .NET runtime patching and is a technique mostly used by plugin developers. It works on both, Linux and Windows since it does not use platform specific code.

It allows us to do changes to the original Unturned code where there aren't any hooks or events that would allow it.

The project has been restructured and since there are no hardcoded local-dependencies anymore, the missing .csproj has been readded. People who want to contribute only have to copy Unturneds files into `unturned-libs` directory (the files in that directory are ignored by git). The Community project has been also moved to its own sub directory. This makes the workspace a lot cleaner and clearer.

**Note:** 
After this pull request a simple `git clone ...` will not work anymore, it needs to be `git clone --recursive ...` since Harmony has been added as a sub gitmodule. Of course we can just include the pre-compiled dll instead but I'm against that. It's a security risk to include compiled binaries.

The output path (e.g. `/bin/Release` or `/bin/Debug`) will *only* contain the required module files. Example: 
image

This is how the repo looks like atm: https://github.com/Trojaner25/Unturned-3.x-Community-Module/tree/mod

Don't forget to [check out the updated Readme too](https://github.com/Trojaner25/Unturned-3.x-Community-Module/blob/mod/README.md)

Todo: Maybe add a `build.bat` which copies the unturned-libs and then copies the output files to the Unturned module directory

### CODE REVIEW

**Comment by SDGNelson** [comment]
Thanks for this cleanup commit! It looks like aviadmini agrees with you, but do you think we could get some feedback from other plugin devs before merging this? Want to make sure pull requests are agreed upon before officially integrating especially with 3rd party libraries.

**Comment by RoyIL** [comment]
YES!

**Comment by LuxarPL** [comment]
_stamp of approval_

**Comment by Adamv21** [comment]
stamp of approval

**Comment by persiafighter** [comment]
I'd definitely agree to this. It's a breeze to use honestly.

**Comment by Jonnyfencing1** [comment]
Yup 11/10

**Comment by Exposed-Avery** [comment]
Easily agreed upon.

**Comment by Arechii** [comment]
stamp of approval

**Comment by Alekaei** [comment]
Yes

**Comment by aviadmini** [comment]
That's a party 🎉

**Comment by Alekaei** [comment]
i hate parties

**Comment by N1GHTPATROL** [comment]
**_stamp of approval_**

**Comment by wandereri** [comment]
It's a good idea. I support the authors.

**Comment by Trojaner25** [comment]
CLA has been signed however since the pull request was done before it was added, it won't show here

**Comment by SDGNelson** [comment]
I've gotten a few opposing PMs around this PR - I think the main opposition is that it doesn't make sense to officially include a feature which modifies the official assemblies, i.e. it's redundant. On the other hand I can't make all the core code changes everyone could possibly want, so I'll be merging this in for this week's update.

**Comment by Trojaner25** [comment]
The main idea behind adding Harmony was to speed up development; as you said its not easy to add all change requests to Unturneds code. It's not for replacing original code; but to hook it, e.g. do stuff before or after a certain method.

**Comment by Trojaner25** [comment]
There should be a communication channel between you and the CM contributors, so we can discuss changes etc. For example, we could talk about the streaming audio feature before I start writing the related code, otherwise I may spent hours working on it and you may deny it for some reason.

**Comment by SDGNelson** [comment]
Since the development of the module is completely public I think it would be ideal to keep the communication open. Maybe we all use the issues page here to discuss potential features?

**Comment by Trojaner25** [comment]
We can do it public too, however GitHub is a slow communication channel compared to something like discord, IRC, Slack etc...

**Comment by aviadmini** [comment]
I wonder how many weeks it would take to get a feature discussed, added and published...

**Comment by ChubbyQuokka** [comment]
@aviadmini We're up to two!

**Comment by Trojaner25** [comment]
Any updates? @SDGNelson

**Comment by SDGNelson** [comment]
Has now been merged in - future pull requests will likely go through faster. This next patch will likely go onto a preview branch on Steam rather than directly onto the public branch.

**Comment by Trojaner25** [comment]
Thanks.

**Comment by SDGNelson** [comment]
This is now on the preview branch and will be in Friday's update.

**Pull request merged**
